### ISSUE TITLE
How to specify IEC qualifying symbols for control blocks

### ISSUE THREAD

**Issue by mrnuke** [bobc/kicad-symgen#5]
IEC qualifying symbols are placed near the top center of a symbol or symbol element. For example, an 8-bit shift register would have "SRG8" test in the control block.

Is there a way to specify this in the descriptor of the symgen?

**Comment by bobc** [comment]
I've implemented a fix so that labels for control blocks are placed at the top center.

**Comment by bobc** [comment]
I am presuming this issue is fixed, please re-open if not.
