### ISSUE TITLE
Pin offset and alignment for top and bottom

### ISSUE THREAD

**Issue by jcyrax** [bobc/kicad-symgen#6]
Hi
Great tool!

I was trying out and couldn't figure how to make pins on top and bottom center aligned. I saw todo in docs, but asking just in case I missed some configuration.
This is what I get now.
![align](https://user-images.githubusercontent.com/16546947/34910849-2a64e448-f8c6-11e7-8108-b2c8c9f88b95.png)
Is it possible to insert offset or alignment?
Maybe, if you plan to add it, automatic width of symbol would be cool.

**Comment by bobc** [comment]
If you add "C" to the position parameter it will center the pins, e.g. 

```
128 GND PI BC
137 GND PI BC
36 VCCAUX PI TC
66 VCCAUX PI TC
```

I've just added automatic width, will push a new version soon.

**Comment by jcyrax** [comment]
Thanks, that helps.
