### ISSUE TITLE
Background fill and file problem

### ISSUE THREAD

**Issue by jcyrax** [bobc/kicad-symgen#7]
I have a problem, maybe bug.

1) Some symbols don't have background filled for power units and/or other units.
2) Generated library file contains duplicate entries for pins and graphics.

Here is example script that generates this problem for me https://www.dropbox.com/s/nddzbn2wozs0rgh/symgen_test.txt?dl=0

Here is resultant lib files
https://www.dropbox.com/s/8m3b90dlbt20cm6/testlib.lib?dl=0
https://www.dropbox.com/s/mcr8f4azmv6gc8e/testlib.dcm?dl=0

There are duplicate GND and VCC pins and also S records for rectangle I think. Also its not filled, but script has set to fill back.

**Comment by bobc** [comment]
Hi, thanks for your feedback!

I have fixed the background fill. The duplicate pins are the de Morgan logic equivalents which symgen generates automatically. The duplicate power pins are unnecessary though, I have committed a fix for that also.

I have done a lot of refactoring and several new features, I aim to maintain backward compatibility but sometimes errors creep in. If you see any other problems please let me know.

**Comment by jcyrax** [comment]
Thanks, fill works fine now.
