### ISSUE TITLE
Not unit enable pin rotation

### ISSUE THREAD

**Issue by jcyrax** [bobc/kicad-symgen#8]
I have one more issue. For this symbol with NOT unit, enable pin is horizontal not vertical. For buffer there is no such problem as I see.

COMP 74LVC2G240 U
%fill back
FPLIST
SOT?505?2*
SOT?765?1*
SOT?833?1*
SOT?1089*
SOT?996?2*
SOT?1116*
SOT?1203*
DESC Dual inverter, active-low enable, three-state, SOT-505-2/SOT-765-1/SOT-833-1/SOT-1089/SOT-996-2/SOT-1116/SOT-1203
KEYW dual NOT gate three state
DOC https://assets.nexperia.com/documents/data-sheet/74LVC2G240.pdf
UNIT NOT
1 ~ I B
2 ~ I L
6 ~ O R
UNIT NOT
7 ~ I B
5 ~ I L
3 ~ O R
UNIT PWR SEP
4 GND PI BC
8 VCC PI TC
END

![image](https://user-images.githubusercontent.com/16546947/36601532-031ef276-18be-11e8-8c44-feab50e36c66.png)

**Comment by bobc** [comment]
Looks like a bug, I'll look into it.

**Comment by bobc** [comment]
Should be fixed now!

**Comment by jcyrax** [comment]
Thanks, works now.
